tabs:
  -
    name: 'Copy'
    sortOrder: 1
    fields:
      -
        name: 'Content'
        handle: 'ucontent'
        instructions: ''
        searchable: 1
        type: verbb\supertable\fields\SuperTableField
        translationMethod: none
        translationKeyFormat: ''
        fieldGroup: 1
        required: true
        settings:
          fieldLayout: row
          propagationMethod: none
          selectionLabel: 
          minRows: 
          maxRows: 
          staticField: 1
          blockTypes:
            new:
              fields:
                new1:
                  name: 'Eyebrow'
                  handle: 'eyebrow'
                  instructions: ''
                  searchable: true
                  translationMethod: site
                  translationKeyFormat: null
                  type: craft\fields\PlainText
                  required: false
                  typesettings:
                    placeholder: ''
                    code: ''
                    multiline: ''
                    initialRows: '4'
                    charLimit: ''
                    columnType: text
                  contentColumnType: text
                  fieldGroup: 1
                new2:
                  name: 'Heading'
                  handle: 'heading'
                  instructions: ''
                  searchable: true
                  translationMethod: site
                  translationKeyFormat: null
                  type: craft\fields\PlainText
                  required: true
                  typesettings:
                    placeholder: ''
                    code: ''
                    multiline: true
                    initialRows: '2'
                    charLimit: ''
                    columnType: text
                  contentColumnType: text
                  fieldGroup: 1
                new3:
                  name: 'Subheading'
                  handle: 'subheading'
                  instructions: ''
                  searchable: true
                  translationMethod: site
                  translationKeyFormat: null
                  type: craft\fields\PlainText
                  typesettings:
                    placeholder: ''
                    code: ''
                    multiline: true
                    initialRows: '4'
                    charLimit: ''
                    columnType: text
                  contentColumnType: text
                  fieldGroup: 1
                new4:
                  name: 'Copy'
                  handle: 'copy'
                  instructions: 
                  searchable: 
                  searchable: 1
                  type: craft\redactor\Field
                  translationMethod: site
                  translationKeyFormat: 
                  typesettings:
                    redactorConfig: ''
                    availableVolumes: '*'
                    removeInlineStyles: 1
                    removeEmptyTags: 1
                    removeNbsp: 1
                    purifyHtml: 1
                    purifierConfig: 
                  columnType: text
                  fieldGroup: 1
      -
        name: Media
        handle: media
        instructions: ''
        searchable: true
        translationMethod: site
        translationKeyFormat: null
        type: craft\fields\Matrix
        settings:
          minBlocks: ''
          maxBlocks: ''
          contentTable: '{{%matrixcontent_media}}'
          propagationMethod: none
          blockTypes:
            new1:
              name: Image
              handle: image
              fields:
                new1:
                  name: Image
                  handle: image
                  required: true
                  instructions: ''
                  searchable: true
                  translationMethod: site
                  translationKeyFormat: null
                  type: craft\fields\Assets
                  typesettings:
                    useSingleFolder: '1'
                    defaultUploadLocationSource: '{{volume:local}}'
                    defaultUploadLocationSubpath: ''
                    singleUploadLocationSource: '{{volume:local}}'
                    singleUploadLocationSubpath: '{owner.slug}/images'
                    restrictFiles: '1'
                    allowedKinds:
                      - image
                    sources: '*'
                    source: null
                    targetSiteId: null
                    viewMode: large
                    limit: '1'
                    selectionLabel: ''
                    localizeRelations: '1'
                    validateRelatedElements: ''
                  contentColumnType: string
                  fieldGroup: null
            new2:
              name: Video
              handle: video
              fields:
                new1:
                  name: 'Video Url'
                  handle: videoUrl
                  instructions: ''
                  searchable: true
                  translationMethod: site
                  translationKeyFormat: null
                  type: craft\fields\PlainText
                  settings:
                    placeholder: ''
                    code: ''
                    multiline: ''
                    initialRows: '2'
                    charLimit: ''
                    columnType: text
                  contentColumnType: text
                  fieldGroup: null
                new2:
                  name: 'Autoplay'
                  handle: autoplay
                  instructions: ''
                  searchable: true
                  translationMethod: site
                  translationKeyFormat: null
                  type: craft\fields\Lightswitch
                  settings:
                    on: '1'
                  contentColumnType: boolean
                  fieldGroup: null
        contentColumnType: string
        fieldGroup: 1
                      