tabs:
  -
    name: Copy
    sortOrder: 1
    fields:
      -
        name: 'Hero Image'
        handle: heroImage
        instructions: ''
        searchable: true
        translationMethod: site
        translationKeyFormat: null
        type: craft\fields\Assets
        settings:
          useSingleFolder: '1'
          defaultUploadLocationSource: 'volume:072b84fb-d380-4a33-8f7f-65104157db8b'
          defaultUploadLocationSubpath: images/
          singleUploadLocationSource: 'volume:072b84fb-d380-4a33-8f7f-65104157db8b'
          singleUploadLocationSubpath: images/
          restrictFiles: '1'
          allowedKinds:
            - image
          sources:
            - 'volume:072b84fb-d380-4a33-8f7f-65104157db8b'
          source: null
          targetSiteId: null
          viewMode: large
          limit: '1'
          selectionLabel: ''
          localizeRelations: false
          validateRelatedElements: ''
        contentColumnType: string
        fieldGroup: null
      -
        name: Downloads
        handle: downloads
        instructions: 'Attach PDFs'
        searchable: true
        translationMethod: site
        translationKeyFormat: null
        type: craft\fields\Assets
        settings:
          useSingleFolder: '1'
          defaultUploadLocationSource: 'volume:072b84fb-d380-4a33-8f7f-65104157db8b'
          defaultUploadLocationSubpath: pdfs/
          singleUploadLocationSource: 'volume:072b84fb-d380-4a33-8f7f-65104157db8b'
          singleUploadLocationSubpath: pdfs/
          restrictFiles: '1'
          allowedKinds:
            - pdf
          sources:
            - 'volume:072b84fb-d380-4a33-8f7f-65104157db8b'
          source: null
          targetSiteId: null
          viewMode: large
          limit: ''
          selectionLabel: ''
          localizeRelations: false
          validateRelatedElements: ''
        contentColumnType: string
        fieldGroup: null
      -
        name: Salary
        handle: salary
        instructions: ''
        searchable: true
        translationMethod: none
        translationKeyFormat: null
        type: craft\fields\Number
        settings:
          defaultValue: '65000'
          min: '1'
          max: ''
          decimals: 2
          size: null
          prefix: ''
          suffix: ''
        contentColumnType: integer(10)
        fieldGroup: null
