name: 'Heading'
handle: heading
instructions: ''
searchable: true
translationMethod: site
translationKeyFormat: null
type: craft\fields\PlainText
fieldGroup: null
settings:
  placeholder: ''
  code: ''
  multiline: ''
  initialRows: '2'
  charLimit: ''
  columnType: text
  contentColumnType: text
