name: 'Matrix Test'
handle: matrixTest
instructions: ''
searchable: true
translationMethod: site
translationKeyFormat: null
type: craft\fields\Matrix
settings:
  minBlocks: ''
  maxBlocks: ''
  contentTable: '{{%matrixcontent_matrixTest}}'
  propagationMethod: none
  blockTypes:
    new:
      fields:
        new1:
          name: Email
          handle: email
          instructions: ''
          searchable: true
          translationMethod: site
          translationKeyFormat: null
          type: craft\fields\PlainText
          settings:
            placeholder: ''
            code: ''
            multiline: ''
            initialRows: '2'
            charLimit: ''
            columnType: text
            contentColumnType: text
            fieldGroup: null
        new2:
          name: Url
          handle: url
          instructions: ''
          searchable: true
          translationMethod: site
          translationKeyFormat: null
          type: craft\fields\PlainText
          settings:
            placeholder: ''
            code: ''
            multiline: ''
            initialRows: '2'
            charLimit: ''
            columnType: text
            contentColumnType: text
            fieldGroup: null
