name: 'My New Matrix'
handle: myNewMatrix
instructions: ''
searchable: true
translationMethod: site
translationKeyFormat: null
type: craft\fields\Matrix
settings:
  minBlocks: ''
  maxBlocks: ''
  contentTable: '{{%matrixcontent_myNewMatrix}}'
  propagationMethod: none
  blockTypes:
    new:
      fields:
        new1:
          name: 'Hero Image'
          handle: heroImage
          instructions: ''
          searchable: true
          translationMethod: site
          translationKeyFormat: null
          type: craft\fields\Assets
          settings:
            useSingleFolder: '1'
            defaultUploadLocationSource: 'volume:072b84fb-d380-4a33-8f7f-65104157db8b'
            defaultUploadLocationSubpath: images/
            singleUploadLocationSource: 'volume:072b84fb-d380-4a33-8f7f-65104157db8b'
            singleUploadLocationSubpath: images/
            restrictFiles: '1'
            allowedKinds:
              - image
            sources:
              - 'volume:072b84fb-d380-4a33-8f7f-65104157db8b'
            source: null
            targetSiteId: null
            viewMode: large
            limit: '1'
            selectionLabel: ''
            localizeRelations: false
            validateRelatedElements: ''
          contentColumnType: string
          fieldGroup: null
        new2:
          name: Downloads
          handle: downloads
          instructions: 'Attach PDFs'
          searchable: true
          translationMethod: site
          translationKeyFormat: null
          type: craft\fields\Assets
          settings:
            useSingleFolder: '1'
            defaultUploadLocationSource: 'volume:072b84fb-d380-4a33-8f7f-65104157db8b'
            defaultUploadLocationSubpath: pdfs/
            singleUploadLocationSource: 'volume:072b84fb-d380-4a33-8f7f-65104157db8b'
            singleUploadLocationSubpath: pdfs/
            restrictFiles: '1'
            allowedKinds:
              - pdf
            sources:
              - 'volume:072b84fb-d380-4a33-8f7f-65104157db8b'
            source: null
            targetSiteId: null
            viewMode: large
            limit: ''
            selectionLabel: ''
            localizeRelations: false
            validateRelatedElements: ''
          contentColumnType: string
          fieldGroup: null
