name: 'Salary'
handle: salary
instructions: ''
searchable: true
translationMethod: none
translationKeyFormat: null
type: craft\fields\Number
settings:
  defaultValue: '65000'
  min: '1'
  max: ''
  decimals: 2
  size: null
  prefix: ''
  suffix: ''
contentColumnType: integer(10)
fieldGroup: null